"""add creator key escrow and key requests

Revision ID: 29a61a810469
Revises: e516c15817d7
Create Date: 2026-08-15 12:41:19.090924

"""
from alembic import op
import sqlalchemy as sa


revision = '29a61a810469'
down_revision = 'e516c15817d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_key_escrows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cultural_object_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('last_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cultural_object_id'], ['cultural_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_key_escrows_cultural_object_id'), 'creator_key_escrows', ['cultural_object_id'], unique=True)
    op.create_index(op.f('ix_creator_key_escrows_user_id'), 'creator_key_escrows', ['user_id'], unique=False)
    op.create_table('creator_key_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cultural_object_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cultural_object_id'], ['cultural_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_key_requests_cultural_object_id'), 'creator_key_requests', ['cultural_object_id'], unique=False)
    op.create_index(op.f('ix_creator_key_requests_user_id'), 'creator_key_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creator_key_requests_user_id'), table_name='creator_key_requests')
    op.drop_index(op.f('ix_creator_key_requests_cultural_object_id'), table_name='creator_key_requests')
    op.drop_table('creator_key_requests')
    op.drop_index(op.f('ix_creator_key_escrows_user_id'), table_name='creator_key_escrows')
    op.drop_index(op.f('ix_creator_key_escrows_cultural_object_id'), table_name='creator_key_escrows')
    op.drop_table('creator_key_escrows')
    # ### end Alembic commands ###