"""add creator key hash to cultural objects

Revision ID: 6d700308a9e7
Revises: 18e5eabc3096
Create Date: 2026-08-15 02:52:00.977029

"""
from alembic import op
import sqlalchemy as sa


revision = '6d700308a9e7'
down_revision = '18e5eabc3096'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cultural_objects', sa.Column('creator_key_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cultural_objects', 'creator_key_hash')
    # ### end Alembic commands ###